POST http://localhost:3000/products
Content-Type: application/json

{
  "description":"Desc",
  "name":"Product 1",
  "purchasePrice": 102.90,
  "salesPrice": 123.20,
  "stock": 10
}

####

POST http://localhost:3000/clients
Content-Type: application/json

{
  "name":"Robson Silva",
  "email":"robson@gmail.com",
  "document":"12345678989",
  "street":"Rua Janeiro",
  "number":"15",
  "complement":"complemento",
  "city":"Jandira",
  "state":"SP",
  "zipCode":"06655987"
}

####

POST http://localhost:3000/checkout
Content-Type: application/json

{
  "clientId": "d80988a7-a11e-4957-98a2-2e6c077385d3",
  "products": [
    "bedf09e7-b9b7-41a3-8256-92c09bca7def"
  ]
}

####

GET http://localhost:3000/invoice/685b5631-b33a-4968-912f-d349d7b41ab7
Content-Type: application/json

####

GET http://localhost:3000/invoice?id=685b5631-b33a-4968-912f-d349d7b41ab7
Content-Type: application/json